
[context.branch-deploy]
  command = "make spellingbee"

[[redirects]]
  from = "/#projects"
  to = "/"
  status = 301
  force = true
  query = {path = ":path"}
  conditions = {Language = ["en"], Country = ["US"], Role = ["admin"]}
